# Which agentic-lib workflow schedule should be used?
schedule: schedule-1
sourcesLimit: 8
documentsLimit: 32
featuresWipLimit: 3
featureDevelopmentIssuesWipLimit: 1
maintenanceIssuesWipLimit: 3
attemptsPerBranch: 2
attemptsPerIssue: 2
# Mapping for writeable filepaths
# These are used as defaults when invoking workflows and as allowed patterns for agents
writeableFilepaths:
  docs:         "docs/"
  features:     "features/"
  library:      "library/"
  src:          "src/lib/"
  tests:        "tests/unit/"
  dependencies: "package.json"
  readme:       "README.md"
  sources:      "SOURCES*.md"
