# Which agentic-lib workflow schedule should be used?
schedule: schedule-1

# Mapping for read-only filepaths
# These are used as defaults when invoking workflows
readOnlyFilepaths:
  mission: "MISSION.md"
  contributing: "CONTRIBUTING.md"
  formattingFile: ".prettierrc"
  lintingFile: "eslint.config.js"

# Mapping for writeable filepaths
# These are used as defaults when invoking workflows and as allowed patterns for agents
writeableFilepaths:
  docs:         "docs/"
  features:     "features/"
  library:      "library/"
  src:          "src/lib/"
  tests:        "tests/unit/"
  dependencies: "package.json"
  readme:       "README.md"
  sources:      "SOURCES*.md"

# Execution commands
buildScript: "npm run build"
testScript: "npm test"
mainScript: "npm run start"

# How many sources should exist for document fetching?
sourcesLimit: 8

# How many documents should exist in the library?
documentsLimit: 32

# How many features should exist concurrently open for issue creation?
featuresWipLimit: 3

# How many issues should be open to be picked up?
featureDevelopmentIssuesWipLimit: 1
maintenanceIssuesWipLimit: 3

# How many attempts should be made to work on an issue?
attemptsPerBranch: 2
attemptsPerIssue: 2
