services:
  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=sqs,s3
      - DEBUG=1
    ports:
      - "4566:4566"
      - "4571:4571"

  replay:
    build: .
    environment:
      S3_ENDPOINT: http://localstack:4566
      SQS_ENDPOINT: http://localstack:4566
      SOURCE_QUEUE_URL: http://localstack:4566/000000000000/source-queue-local
      REPLAY_QUEUE_URL: http://localstack:4566/000000000000/replay-queue-local
      BUCKET_NAME: local-bucket
      OBJECT_PREFIX: local/
    depends_on:
      - localstack
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: ["npm", "run", "replay"]
