# .github/workflows/issue-creator.yml
#
# This file is part of the example suite for `agentic-lib` see: https://github.com/xn-intenton-z2a/agentic-lib
# This file is licensed under the MIT License. For details, see LICENSE-MIT

name: Create Issue
concurrency: create-issue
run-name: "Create Issue"

on:
  workflow_dispatch:
    inputs:
      prompt:
        description: 'Text to drive the issue creation (if "house choice", a currently random prompt will be selected). e.g. "Make an improvement to tests."'
        required: false
        type: string
        default: 'house choice'
  schedule:
    - cron: '0 4 * * *' # schedule-1
    #- cron: '0 */2 * * *' # schedule-2
    #- cron: '*/15 * * * *' # schedule-3

jobs:

  # If the issue title is "house choice", a random prompt will be selected from the prompt library otherwise the supplied title will be used.
  select-prompt:
    runs-on: ubuntu-latest
    outputs:
      prompt: ${{ steps.extract.outputs.prompt }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Select prompt from ./prompts
        id: select
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            let prompt = '${{ github.event.inputs.prompt }}';
            if (prompt === 'house choice') {
              const promptsDir = './prompts';
              // Get all items in the directory
              const items = fs.readdirSync(promptsDir);
              // Filter only the files (exclude directories)
              const files = items.filter(item => {
                const filePath = path.join(promptsDir, item);
                return fs.lstatSync(filePath).isFile();
              });
            
              if (files.length === 0) {
                core.setFailed('No prompt files found in the prompts directory.');
              } else {
                // Select a random file
                const randomFile = files[Math.floor(Math.random() * files.length)];
                const filePath = path.join(promptsDir, randomFile);
                prompt = fs.readFileSync(filePath, 'utf8');
              }
            }
              
            core.setOutput('prompt', prompt);
            core.info(`prompt: ${prompt}`);

  generate-issue:
    needs:
      - select-prompt
    permissions:
      contents: write
      issues: write
      id-token: write
    uses: 'xn-intenton-z2a/agentic-lib/.github/workflows/wfr-generate-issue.yml@2.15.0'
    with:
      prompt: ${{ needs.select-prompt.outputs.prompt }}
      target: ${{ inputs.target || 'src/lib/main.js' }}
      testFile: ${{ inputs.testFile || 'tests/unit/main.test.js' }}
      readmeFile: 'README.md'
      missionFile: 'MISSION.md'
      contributingFile: 'CONTRIBUTING.md'
      dependenciesFile: 'package.json'
      buildScript: 'npm run build'
      testScript: 'npm test'
      mainScript: ${{ vars.MAIN_SCRIPT || 'npm run start' }}
      model: ${{ vars.CHATGPT_API_MODEL || 'o3-mini' }}
      npmAuthOrganisation: '@xn-intenton-z2a'
    secrets:
      CHATGPT_API_SECRET_KEY: ${{ secrets.CHATGPT_API_SECRET_KEY }}
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  create-issue:
    needs:
      - select-prompt
      - generate-issue
    permissions:
      issues: write
      id-token: write
    uses: 'xn-intenton-z2a/agentic-lib/.github/workflows/wfr-create-issue.yml@2.15.0'
    with:
      issueTitle: ${{ needs.generate-issue.outputs.issueTitle }}
      issueBody: ${{ needs.generate-issue.outputs.issueDescription }}
